/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.List;

public class App 
{
    public String getGreeting() 
    {
        return "Hello World!";

    }

    public static void main(String[] args) 
    {
        ZipIt zipIt = new ZipIt();

        List<Integer> intList1 = List.of(1, 2, 3, 4);
        List<Integer> intList2 = List.of(5, 6, 7, 8);

        System.out.println(zipIt.zip(intList1, intList2));

        List<String> stringList1 = List.of("Cat", "Dog", "Bird", "Fish", "Frog");
        List<String> stringList2 = List.of("Pig", "Cow", "Sheep");

        System.out.println(zipIt.zip(stringList1, stringList2));

        List<Double> doubleList1 = List.of(1.0, 2.0, 3.0);
        List<Double> doubleList2 = List.of(4.0, 5.0, 6.0, 7.0, 8.0);

        System.out.println(zipIt.zip(doubleList1, doubleList2));

    }
    
}
